#!/usr/bin/env python
"""
Masked wordcloud
================

Using a mask you can generate wordclouds in arbitrary shapes.
"""

from os import path
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import os

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

# get data directory (using getcwd() is needed to support running example in generated IPython notebook)
d = path.dirname(__file__) if "__file__" in locals() else os.getcwd()

# Read the whole text.
text = open(path.join(d, 'eeaao.txt')).read()

# read the mask image
alice_mask = np.array(Image.open(path.join(d, "hotdogfingerspink.png")))

stopwords = set(STOPWORDS)
stopwords.add("said")
stopwords.add("oh")
stopwords.add("ok")
stopwords.add("speaking")
stopwords.add("playing")
stopwords.add("INDISTINCTLY")
stopwords.add("go")
stopwords.add("MANDARIN")
stopwords.add("one")
stopwords.add("YELLING")
stopwords.add("come")
stopwords.add("Huh")
stopwords.add("alphawaymond")
stopwords.add("MAN")
stopwords.add("stop")
stopwords.add("every")
stopwords.add("WOMAN")
stopwords.add("CANTONESE")
stopwords.add("take")
stopwords.add("now")
stopwords.add("Ugh")
stopwords.add("AUTOMATEDVOICE")
stopwords.add("think")
stopwords.add("DOOR")
stopwords.add("know")
stopwords.add("GRUNTING")
stopwords.add("MUSIC")
stopwords.add("GASP")
stopwords.add("GRUNT")
stopwords.add("GRUNTS")
stopwords.add("GASPS")
stopwords.add("SIGHS")
stopwords.add("SIGH")
stopwords.add("CONTINUE")
stopwords.add("CONTINUES")
stopwords.add("SINGING")
stopwords.add("EXCLAIM")
stopwords.add("EXCLAIMS")
stopwords.add("EXCLAIMING")
stopwords.add("CHATTERING")
stopwords.add("SCREAMING")
stopwords.add("DISTORTED")
stopwords.add("COUGHS")
stopwords.add("GROAN")
stopwords.add("GROANS")
stopwords.add("INDISTINCT")
stopwords.add("SCREAM")
stopwords.add("GASPING")
stopwords.add("GROANING")
stopwords.add("OPEN")
stopwords.add("DRAMATIC")
stopwords.add("OFFICER")
stopwords.add("PHONE")
stopwords.add("CHATTER")
stopwords.add("Hey")
stopwords.add("CHUCKLE")
stopwords.add("SCOFFS")
stopwords.add("SUSPENSEFUL")
stopwords.add("OPENS")
stopwords.add("PANTING")
stopwords.add("BUZZING")
stopwords.add("YELL")
stopwords.add("SCREAMS")
stopwords.add("SENTIMENTAL")
stopwords.add("CHUCKLING")
stopwords.add("EXHALES")
stopwords.add("WHIMPERS")
stopwords.add("MUTTERS")
stopwords.add("POWERING")
stopwords.add("us")
stopwords.add("EERIE")
stopwords.add("Uh")
stopwords.add("SHUSH")
stopwords.add("SHUSHES")
stopwords.add("CAR")
stopwords.add("EXCITEDLY")
stopwords.add("MEN")
stopwords.add("FOOTSTEPS")
stopwords.add("APPLAUDING")
stopwords.add("STRAINING")
stopwords.add("SPEECH")
stopwords.add("BABBLING")
stopwords.add("SHARPLY")
stopwords.add("IMITATES")
stopwords.add("TUTTING")
stopwords.add("HORN")
stopwords.add("COCKING")
stopwords.add("CHUCKLES")
stopwords.add("SNARLING")
stopwords.add("YELLS")
stopwords.add("SPEAKS")
stopwords.add("TENSE")
stopwords.add("CLOSE")
stopwords.add("WHISPERING")
stopwords.add("INAUDIBLE")
stopwords.add("RISES")
stopwords.add("gonna")
stopwords.add("Yeah")
stopwords.add("Hello")
stopwords.add("something")
stopwords.add("going")
stopwords.add("CLOSES")
stopwords.add("YOUNG")
stopwords.add("SOMBRE")
stopwords.add("really")
stopwords.add("let")
stopwords.add("got")
stopwords.add("power")
stopwords.add("Please")
stopwords.add("another")
stopwords.add("Whoa")
stopwords.add("still")
stopwords.add("bring")
stopwords.add("will")
stopwords.add("Rick")
stopwords.add("Shh")
stopwords.add("back")
stopwords.add("SLOW")
stopwords.add("MUTED")
stopwords.add("thing")
stopwords.add("even")
stopwords.add("EARPIECECHIMES")
stopwords.add("laundry taxes")
stopwords.add("taxes BAGEL")
stopwords.add("people")
stopwords.add("Ow")
stopwords.add("VOICE")
stopwords.add("Chad")
stopwords.add("WHIRRING")
stopwords.add("LAUGHING")
stopwords.add("SOFTLY")
stopwords.add("Hi")
stopwords.add("things")
stopwords.add("whatever")
stopwords.add("mean")
stopwords.add("see")





wc = WordCloud(background_color="black", max_words=2000, mask=alice_mask,
               stopwords=stopwords, contour_color='black',contour_width=1,scale=1,
               max_font_size=140,relative_scaling=0.25)

# generate word cloud
wc.generate(text)

# create coloring from image
image_colors = ImageColorGenerator(alice_mask)

wc.recolor(color_func=image_colors)
plt.figure(figsize=(10, 10))
plt.imshow(wc, interpolation="bilinear")
wc.to_file("eeaao_output.png")
